apiVersion: kubedb.com/v1alpha2
kind: ClickHouse
metadata:
  name: {{ include "clickhouse.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  version: {{ .Values.version | quote }}
  deletionPolicy: {{ .Values.deletionPolicy | quote }}
{{- if eq .Values.deploymentMode "cluster" }}
  clusterTopology:
    clickHouseKeeper:
      externallyManaged: {{ .Values.clusterTopology.clickHouseKeeper.externallyManaged }}
      spec:
        replicas: {{ .Values.clusterTopology.clickHouseKeeper.replicas }}
        storage:
          storageClassName: {{ .Values.clusterTopology.clickHouseKeeper.storage.storageClassName | quote }}
          accessModes:
{{ toYaml .Values.clusterTopology.clickHouseKeeper.storage.accessModes | indent 12 }}
          resources:
            {{- toYaml .Values.clusterTopology.clickHouseKeeper.storage.resources | nindent 12 }}
    cluster:
      - name: {{ .Values.clusterTopology.cluster.name | quote }}
        shards: {{ .Values.clusterTopology.cluster.shards }}
        replicas: {{ .Values.clusterTopology.cluster.replicas }}
        podTemplate:
          {{- toYaml .Values.clusterTopology.cluster.podTemplate | nindent 10 }}
        storage:
          storageClassName: {{ .Values.clusterTopology.cluster.storage.storageClassName | quote }}
          accessModes:
{{ toYaml .Values.clusterTopology.cluster.storage.accessModes | indent 12 }}
          resources:
            requests:
              storage: {{ .Values.clusterTopology.cluster.storage.resources.requests.storage | quote }}
{{- else }}
  storage:
    accessModes:
{{ toYaml .Values.storage.accessModes | indent 6 }}
    resources:
      {{- toYaml .Values.storage.resources | nindent 6 }}
{{- end }}
